// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ7AVWJf9cO4lmFPb5tCN-eVXj2dJGyBE',
    appId: '1:183155452119:web:d6bd88311749548d84a892',
    messagingSenderId: '183155452119',
    projectId: 'fishfarm-d5334',
    authDomain: 'fishfarm-d5334.firebaseapp.com',
    storageBucket: 'fishfarm-d5334.appspot.com',
    measurementId: 'G-QD8ES5KTTQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApkmXdKOiIeC8ii1iQHkk1tx31v3a7sIM',
    appId: '1:183155452119:android:a3a83cd94c0fc88984a892',
    messagingSenderId: '183155452119',
    projectId: 'fishfarm-d5334',
    storageBucket: 'fishfarm-d5334.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyYtLoTNuSjWYVGmvjSFmWjG4J26BYDg0',
    appId: '1:183155452119:ios:08de0b294f3613a884a892',
    messagingSenderId: '183155452119',
    projectId: 'fishfarm-d5334',
    storageBucket: 'fishfarm-d5334.appspot.com',
    iosClientId: '183155452119-74aagtnrruca01ac6en7majsqarhl2a3.apps.googleusercontent.com',
    iosBundleId: 'com.example.fishfarm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyYtLoTNuSjWYVGmvjSFmWjG4J26BYDg0',
    appId: '1:183155452119:ios:08de0b294f3613a884a892',
    messagingSenderId: '183155452119',
    projectId: 'fishfarm-d5334',
    storageBucket: 'fishfarm-d5334.appspot.com',
    iosClientId: '183155452119-74aagtnrruca01ac6en7majsqarhl2a3.apps.googleusercontent.com',
    iosBundleId: 'com.example.fishfarm',
  );
}
